/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-11-23 02:39:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0,minimum-scale=0,maximum-scale=10,user-scalable=yes\">\r\n");
      out.write("<meta http-equiv=\"imagetoolbar\" content=\"no\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=10,chrome=1\">\r\n");
      out.write("<title>로그인 | 이비가짬뽕</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://ebiga.co.kr/home/css/default.css?ver=161020\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://ebiga.co.kr/home/skin/member/basic/style.css?ver=161020\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://ebiga.co.kr/home/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://fontawesome.io/assets/font-awesome/css/font-awesome.css\">\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!--[if lte IE 8]>\r\n");
      out.write("<script src=\"https://ebiga.co.kr/home/js/html5.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<script>\r\n");
      out.write("// 자바스크립트에서 사용하는 전역변수 선언\r\n");
      out.write("var g5_url       = \"https://ebiga.co.kr/home\";\r\n");
      out.write("var g5_bbs_url   = \"https://ebiga.co.kr/home/bbs\";\r\n");
      out.write("var g5_is_member = \"\";\r\n");
      out.write("var g5_is_admin  = \"\";\r\n");
      out.write("var g5_is_mobile = \"\";\r\n");
      out.write("var g5_bo_table  = \"\";\r\n");
      out.write("var g5_sca       = \"\";\r\n");
      out.write("var g5_editor    = \"\";\r\n");
      out.write("var g5_cookie_domain = \"\";\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"https://ebiga.co.kr/home/js/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("<script src=\"https://ebiga.co.kr/home/js/jquery.menu.js?ver=161020\"></script>\r\n");
      out.write("<script src=\"https://ebiga.co.kr/home/js/common.js?ver=161020\"></script>\r\n");
      out.write("<script src=\"https://ebiga.co.kr/home/js/wrest.js?ver=161020\"></script>\r\n");
      out.write("<script src=\"https://ebiga.co.kr/home/js/script.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- 로그인 시작 { -->\r\n");
      out.write("<div id=\"mb_login\" class=\"mbskin\">\r\n");
      out.write("    <h1>로그인</h1>\r\n");
      out.write("\r\n");
      out.write("    <form name=\"flogin\" action=\"loginForm.bo\" onsubmit=\"return flogin_submit(this);\" method=\"post\">\r\n");
      out.write("    <input type=\"hidden\" name=\"url\" value=\"https%3A%2F%2Febiga.co.kr%2Fhome%2Fbbs%2Fboard.jsp%3Fbo_table%3Dvideo\">\r\n");
      out.write("\r\n");
      out.write("    <fieldset id=\"login_fs\">\r\n");
      out.write("        <legend>회원로그인</legend>\r\n");
      out.write("        <label for=\"login_id\" class=\"login_id\">회원아이디<strong class=\"sound_only\"> 필수</strong></label>\r\n");
      out.write("        <input type=\"text\" name=\"mb_id\" id=\"login_id\" required class=\"frm_input required\" size=\"20\" maxLength=\"20\">\r\n");
      out.write("        <label for=\"login_pw\" class=\"login_pw\">비밀번호<strong class=\"sound_only\"> 필수</strong></label>\r\n");
      out.write("        <input type=\"password\" name=\"mb_password\" id=\"login_pw\" required class=\"frm_input required\" size=\"20\" maxLength=\"20\">\r\n");
      out.write("        <input type=\"submit\" value=\"로그인\" class=\"btn_submit\">\r\n");
      out.write("        <input type=\"checkbox\" name=\"auto_login\" id=\"login_auto_login\">\r\n");
      out.write("        <label for=\"login_auto_login\">자동로그인</label>\r\n");
      out.write("    </fieldset>\r\n");
      out.write("\r\n");
      out.write("    <aside id=\"login_info\">\r\n");
      out.write("        <h2>회원로그인 안내</h2>\r\n");
      out.write("        <p>\r\n");
      out.write("            회원아이디 및 비밀번호가 기억 안나실 때는 아이디/비밀번호 찾기를 이용하십시오.<br>\r\n");
      out.write("            아직 회원이 아니시라면 회원으로 가입 후 이용해 주십시오.\r\n");
      out.write("        </p>\r\n");
      out.write("        <div>\r\n");
      out.write("            <a href=\"https://ebiga.co.kr/home/bbs/password_lost.jsp\" target=\"_blank\" id=\"login_password_lost\" class=\"btn02\">아이디 비밀번호 찾기</a>\r\n");
      out.write("            <a href=\"joinForm.jsp\" class=\"btn01\">회원 가입</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </aside>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"btn_confirm\">\r\n");
      out.write("        <a href=\"../index.jsp\">메인으로 돌아가기</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("    $(\"#login_auto_login\").click(function(){\r\n");
      out.write("        if (this.checked) {\r\n");
      out.write("            this.checked = confirm(\"자동로그인을 사용하시면 다음부터 회원아이디와 비밀번호를 입력하실 필요가 없습니다.\\n\\n공공장소에서는 개인정보가 유출될 수 있으니 사용을 자제하여 주십시오.\\n\\n자동로그인을 사용하시겠습니까?\");\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function flogin_submit(f)\r\n");
      out.write("{\r\n");
      out.write("    return true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- } 로그인 끝 -->\r\n");
      out.write("\r\n");
      out.write("<!-- ie6,7에서 사이드뷰가 게시판 목록에서 아래 사이드뷰에 가려지는 현상 수정 -->\r\n");
      out.write("<!--[if lte IE 7]>\r\n");
      out.write("<script>\r\n");
      out.write("$(function() {\r\n");
      out.write("    var $sv_use = $(\".sv_use\");\r\n");
      out.write("    var count = $sv_use.length;\r\n");
      out.write("\r\n");
      out.write("    $sv_use.each(function() {\r\n");
      out.write("        $(this).css(\"z-index\", count);\r\n");
      out.write("        $(this).css(\"position\", \"relative\");\r\n");
      out.write("        count = count - 1;\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
